version: '3'

services:
  objectstorage:
    image: bitnami/minio:2020.2.20-debian-10-r1
    ports:
      - "9000:9000"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
