version: '3'

services:
  objectstorage:
    image: minio/minio:edge-cicd
    ports:
      - "9000:9000"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
