version: '3'

services:
  objectstorage:
    image: bitnami/minio:2025.7.23-debian-12-r5
    ports:
      - "9000:9000"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
