services:
  objectstorage:
    image: rustfs/rustfs:1.0.0
    ports:
      - "9000:9000"
    volumes:
      - objectstorage-data:/data
    environment:
      RUSTFS_ACCESS_KEY: minio_access_key
      RUSTFS_SECRET_KEY: minio_secret_key

volumes:
  objectstorage-data:
